apiVersion: v1
kind: Service
metadata:
  name: authdeploy-service
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30007
